# Generated by Django 5.2.2 on 2025-06-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='text',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
